### ISSUE TITLE
Rosa Arcana Knowledge Fragments on Server

### ISSUE THREAD

**Issue by MaelstromPhx** [MyM-ModpackTeam/ThaumicSkies#3]
Server throws this exception when using the rosa arcana knowledge fragments. ID: 6835:0-7
Works fine in SP

```
java.lang.NullPointerException
        at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:395) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:825) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by MaelstromPhx** [comment]
More testing shows it only happens with the last one in a stack.

**Comment by MaelstromPhx** [comment]
Nothing we can really do about it. It's a mod issue that the mod author won't fix because he has moved on to prepping the 1.8 version of the mod. I'll close the issue since it's not resolvable.
